import React from 'react';
import { Modal } from './Modal.tsx';
import { Button } from './Button.tsx';

interface AISummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  isLoading: boolean;
  summary: string;
}

const LoadingSpinner: React.FC = () => (
    <div className="flex flex-col items-center justify-center gap-4 text-text-secondary">
        <svg className="animate-spin h-12 w-12 text-primary" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        <p className="font-medium">Generating AI Summary...</p>
    </div>
);

export const AISummaryModal: React.FC<AISummaryModalProps> = ({ isOpen, onClose, isLoading, summary }) => {
    
    // Simple markdown-to-HTML
    const formattedSummary = summary
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/^- (.*)/gm, '<li>$1</li>')
        .replace(/(<li>.*<\/li>)/gs, '<ul>$1</ul>')
        .replace(/\n/g, '<br />');


    const footerContent = (
      <Button onClick={onClose}>Close</Button>
    );

    return (
        <Modal 
            isOpen={isOpen} 
            onClose={onClose} 
            title="AI Clinical Summary" 
            footer={footerContent}
        >
            <div className="min-h-[200px] flex flex-col">
                {isLoading ? (
                    <div className="flex-1 flex items-center justify-center">
                        <LoadingSpinner />
                    </div>
                ) : (
                    <div>
                        <div dangerouslySetInnerHTML={{ __html: formattedSummary }} className="prose prose-sm dark:prose-invert max-w-none" />
                        <div className="mt-6 p-3 bg-amber-500/10 border border-amber-500/20 rounded-md text-xs text-amber-600 dark:text-amber-300">
                            <strong>Disclaimer:</strong> This summary is generated by an AI and is for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.
                        </div>
                    </div>
                )}
            </div>
        </Modal>
    );
};
