import React from 'react';
import { Modal } from '../common/Modal.tsx';
import { Button } from '../common/Button.tsx';
import { Input } from '../common/Input.tsx';

interface MfaSetupModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const MfaSetupModal: React.FC<MfaSetupModalProps> = ({ isOpen, onClose }) => {
    
    // In a real app, this would be generated by the backend
    const mockQrCodeUrl = "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=otpauth://totp/ChiHealth:user@example.com?secret=JBSWY3DPEHPK3PXP&issuer=ChiHealth";
    const mockSetupKey = "JBSWY3DPEHPK3PXP";

    const footer = (
        <Button onClick={onClose}>Close</Button>
    );
    
    return (
        <Modal isOpen={isOpen} onClose={onClose} title="Set Up Multi-Factor Authentication" footer={footer}>
            <div className="space-y-4">
                <p className="text-sm text-text-secondary">
                    1. Scan this QR code with your authenticator app (e.g., Google Authenticator, Authy).
                </p>
                <div className="flex justify-center p-4 bg-white rounded-md">
                    <img src={mockQrCodeUrl} alt="MFA QR Code" />
                </div>
                <p className="text-sm text-text-secondary text-center">
                    Can't scan? Enter this setup key manually: <br />
                    <strong className="font-mono text-text-primary">{mockSetupKey}</strong>
                </p>
                 <p className="text-sm text-text-secondary">
                    2. Enter the 6-digit code from your app to verify and complete setup.
                </p>
                <form className="flex items-center gap-4">
                    <Input label="Verification Code" name="mfaCode" placeholder="123456" required />
                    <Button type="submit" style={{marginTop: '1.75rem'}}>Verify & Enable</Button>
                </form>
            </div>
        </Modal>
    );
};
